import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AlertTriangle, CalendarClock, CheckCircle2, Clock3, ShoppingCart, Users } from 'lucide-react';
import AppShell from '@/components/AppShell';
import CrmActions,{CompleteFollowup} from '@/components/CrmActions';
import { adminClient } from '@/lib/supabase-admin';
import { getCurrentProfile } from '@/lib/supabase-server';

export const dynamic='force-dynamic';
const valid=new Set(['novo','em_analise','aprovado','separacao','faturado','enviado','finalizado']);
function daysSince(value?:string|null){if(!value)return null;return Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000))}
function dateTime(v:string){return new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
export default async function CrmPage(){
 const p=await getCurrentProfile();if(!p||p.role==='cliente')redirect('/catalogo');const db=adminClient();
 let cq=db.from('customers').select('id,name,trade_name,city,state,whatsapp,phone,email,seller_id,active,profiles!customers_seller_id_fkey(name)').eq('active',true).order('name');
 let oq=db.from('orders').select('id,number,status,total,created_at,customer_id,seller_id').order('created_at',{ascending:false});
 let fq=db.from('crm_followups').select('id,title,notes,channel,status,due_at,customer_id,seller_id,customers(name,trade_name)').eq('status','pendente').order('due_at');
 if(p.role==='vendedor'){cq=cq.eq('seller_id',p.id);oq=oq.eq('seller_id',p.id);fq=fq.eq('seller_id',p.id)}
 const [{data:customers},{data:orders},{data:followups},{data:templates},{data:interactions}]=await Promise.all([cq,oq,fq,db.from('whatsapp_templates').select('id,name,message,context').eq('active',true).order('context').order('name'),p.role==='vendedor'?db.from('crm_interactions').select('id,customer_id,channel,created_at').eq('seller_id',p.id).order('created_at',{ascending:false}).limit(100):db.from('crm_interactions').select('id,customer_id,channel,created_at').order('created_at',{ascending:false}).limit(100)]);const cs:any[]=customers||[],os:any[]=orders||[],fs:any[]=followups||[],ts:any[]=templates||[],ins:any[]=interactions||[];
 const last=new Map<string,any>();const open=new Map<string,number>();for(const o of os){if(o.customer_id&&!last.has(o.customer_id)&&valid.has(o.status))last.set(o.customer_id,o);if(o.customer_id&&['novo','orcamento','em_analise'].includes(o.status))open.set(o.customer_id,(open.get(o.customer_id)||0)+1)}
 const followByCustomer=new Map<string,any>();for(const f of fs)if(!followByCustomer.has(f.customer_id))followByCustomer.set(f.customer_id,f);const interactionByCustomer=new Map<string,any>();for(const i of ins)if(!interactionByCustomer.has(i.customer_id))interactionByCustomer.set(i.customer_id,i);
 const rows=cs.map(c=>{const lo=last.get(c.id);const days=daysSince(lo?.created_at);const f=followByCustomer.get(c.id);let score=0,reason='Carteira ativa';if(f&&new Date(f.due_at).getTime()<Date.now()){score=10000;reason='Follow-up atrasado'}else if(days===null){score=9000;reason='Nunca comprou'}else if(days>60){score=8000+days;reason=`${days} dias sem comprar`}else if(days>30){score=6000+days;reason=`${days} dias sem comprar`}else if((open.get(c.id)||0)>0){score=5000;reason='Pedido aguardando ação'}else score=100-(days||0);return{c,lo,days,f,lastInteraction:interactionByCustomer.get(c.id),score,reason,open:open.get(c.id)||0}}).sort((a,b)=>b.score-a.score);
 const overdue=fs.filter(f=>new Date(f.due_at).getTime()<Date.now()).length;const inactive=rows.filter(r=>r.days===null||(r.days||0)>30).length;const openOrders=[...open.values()].reduce((a,b)=>a+b,0);
 return <AppShell><div className="dashboard-hero crm-hero"><div><span className="eyebrow">CRM COMERCIAL</span><h1>Central de oportunidades</h1><p>Priorize contatos, acompanhe a carteira e registre os próximos passos de cada cliente.</p></div><Link href="/catalogo" className="btn btn-primary"><ShoppingCart size={17}/>Montar pedido</Link></div>
 <section className="dashboard-kpis crm-kpis"><div className="dash-kpi accent-red"><div className="dash-kpi-icon"><AlertTriangle size={22}/></div><span>Follow-ups atrasados</span><strong>{overdue}</strong><small>precisam de ação hoje</small></div><div className="dash-kpi"><div className="dash-kpi-icon"><CalendarClock size={22}/></div><span>Follow-ups pendentes</span><strong>{fs.length}</strong><small>agendamentos em aberto</small></div><div className="dash-kpi accent-orange"><div className="dash-kpi-icon"><Users size={22}/></div><span>Clientes sem comprar</span><strong>{inactive}</strong><small>há mais de 30 dias</small></div><div className="dash-kpi accent-blue"><div className="dash-kpi-icon"><Clock3 size={22}/></div><span>Pedidos aguardando</span><strong>{openOrders}</strong><small>novo, orçamento ou análise</small></div></section>
 <div className="crm-layout"><section className="card crm-priority"><div className="dashboard-card-head"><div><h2>Prioridade da carteira</h2><p>Ordenada automaticamente pelo que exige mais atenção.</p></div><span className="count">{rows.length} clientes</span></div><div className="crm-customer-list">{rows.map(({c,lo,days,f,lastInteraction,reason,open}:any)=><article className="crm-customer" key={c.id}><div className={`crm-priority-bar ${reason.includes('atrasado')||reason.includes('Nunca')?'high':reason.includes('dias')?'medium':'normal'}`}/><div className="customer-avatar">{(c.trade_name||c.name).slice(0,2).toUpperCase()}</div><div className="crm-customer-main"><div><b>{c.trade_name||c.name}</b><small>{[c.city,c.state].filter(Boolean).join(' / ')||'Local não informado'} · {c.profiles?.name||'Sem vendedor'}</small></div><span className={reason.includes('atrasado')||reason.includes('Nunca')?'danger-days':reason.includes('dias')?'warning-days':'badge'}>{reason}</span><div className="crm-customer-meta"><span>Última compra: <b>{lo?new Date(lo.created_at).toLocaleDateString('pt-BR'):'Nunca'}</b></span><span>Pedidos abertos: <b>{open}</b></span>{f&&<span>Próximo contato: <b>{dateTime(f.due_at)}</b></span>}{lastInteraction&&<span>Último contato: <b>{dateTime(lastInteraction.created_at)}</b></span>}</div></div><CrmActions customerId={c.id} sellerId={c.seller_id} whatsapp={c.whatsapp} phone={c.phone} customerName={c.trade_name||c.name} sellerName={p.name||'Nacar Distribuição'} templates={ts} lastOrderNumber={lo?.number||null}/></article>)}</div></section>
 <aside className="card crm-agenda"><div className="dashboard-card-head"><div><h2>Agenda comercial</h2><p>Próximos contatos pendentes.</p></div><CalendarClock size={20}/></div><div className="crm-followups">{fs.slice(0,12).map((f:any)=>{const late=new Date(f.due_at).getTime()<Date.now();return <div className={`crm-followup ${late?'late':''}`} key={f.id}><div><b>{f.customers?.trade_name||f.customers?.name||'Cliente'}</b><small>{f.title}</small><span>{dateTime(f.due_at)} · {f.channel}</span></div><CompleteFollowup id={f.id}/></div>})}{!fs.length&&<div className="dashboard-empty"><CheckCircle2 size={18}/>Nenhum follow-up pendente.</div>}</div></aside></div></AppShell>
}
