import { NextResponse } from 'next/server';
import { adminClient } from '@/lib/supabase-admin';
import { getCurrentProfile } from '@/lib/supabase-server';
const q=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;
const csv=(heads:string[],rows:any[][])=>'\uFEFF'+[heads.map(q).join(';'),...rows.map(r=>r.map(q).join(';'))].join('\r\n');
export async function GET(request:Request,{params}:{params:Promise<{type:string}>}){const p=await getCurrentProfile();if(p?.role!=='admin')return NextResponse.json({error:'Acesso negado'},{status:403});const {type}=await params;const url=new URL(request.url);const from=url.searchParams.get('from');const to=url.searchParams.get('to');const db=adminClient();let content='';let name=type;
 if(type==='pedidos'){let query=db.from('orders').select('number,created_at,status,total,customer_name,customers(name,trade_name,cnpj),seller:profiles!orders_seller_id_fkey(name)').order('created_at',{ascending:false});if(from)query=query.gte('created_at',`${from}T00:00:00.000Z`);if(to)query=query.lte('created_at',`${to}T23:59:59.999Z`);const {data,error}=await query;if(error)return NextResponse.json({error:error.message},{status:500});content=csv(['Pedido','Data','Empresa','CNPJ','Vendedor','Status','Total'],(data||[]).map((x:any)=>[x.number,new Date(x.created_at).toLocaleString('pt-BR'),x.customers?.trade_name||x.customers?.name||x.customer_name,x.customers?.cnpj,x.seller?.name,x.status,Number(x.total||0).toLocaleString('pt-BR',{minimumFractionDigits:2})]));}
 else if(type==='clientes'){const {data,error}=await db.from('customers').select('trade_name,legal_name,cnpj,city,state,phone,whatsapp,email,region,payment_terms,credit_limit,active,seller:profiles!customers_seller_id_fkey(name)').order('trade_name');if(error)return NextResponse.json({error:error.message},{status:500});content=csv(['Fantasia','Razão social','CNPJ','Cidade','UF','Telefone','WhatsApp','E-mail','Região','Vendedor','Condição','Limite','Situação'],(data||[]).map((x:any)=>[x.trade_name,x.legal_name,x.cnpj,x.city,x.state,x.phone,x.whatsapp,x.email,x.region,x.seller?.name,x.payment_terms,x.credit_limit,x.active?'Ativo':'Inativo']));}
 else if(type==='produtos'){const {data,error}=await db.from('products').select('ean,name,brand,category,size,status,suggested_price,cost_price,minimum_price,stock,active,updated_at').order('name');if(error)return NextResponse.json({error:error.message},{status:500});content=csv(['EAN','Produto','Marca','Categoria','Tamanho','Status','Preço sugerido','Preço distribuidor','Preço mínimo','Estoque','Ativo','Atualizado'],(data||[]).map((x:any)=>[x.ean,x.name,x.brand,x.category,x.size,x.status,x.suggested_price,x.cost_price,x.minimum_price,x.stock,x.active?'Sim':'Não',new Date(x.updated_at).toLocaleString('pt-BR')]));}
 else if(type==='vendedores'){const {data,error}=await db.from('profiles').select('name,email,job_title,region,phone,whatsapp,active').eq('role','vendedor').order('name');if(error)return NextResponse.json({error:error.message},{status:500});content=csv(['Nome','E-mail','Cargo','Região','Telefone','WhatsApp','Situação'],(data||[]).map((x:any)=>[x.name,x.email,x.job_title,x.region,x.phone,x.whatsapp,x.active?'Ativo':'Inativo']));}
 else return NextResponse.json({error:'Relatório inválido'},{status:404});
 return new NextResponse(content,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="nacar-${name}-${new Date().toISOString().slice(0,10)}.csv"`}})}
