'use client';
import { useMemo, useState } from 'react';import { ArrowDown, ArrowUp, Check, LocateFixed, MapPin, Navigation, Plus, Route, Save, Trash2 } from 'lucide-react';
type Customer={id:string;name:string;trade_name?:string|null;city?:string|null;state?:string|null;latitude:number|string|null;longitude:number|string|null;priority_score:number;priority_reason:string;distance_km?:number|null;last_visit?:string|null};
type Stop={id:string;customer_id:string;position:number;status:string;priority_reason?:string|null;customer:Customer};
function getPosition(){return new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation?.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0}));}
function distance(a:number,b:number,c:number,d:number){const r=6371,to=(n:number)=>n*Math.PI/180;const x=Math.sin(to(c-a)/2)**2+Math.cos(to(a))*Math.cos(to(c))*Math.sin(to(d-b)/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
export default function RoutePlanner({customers,initialStops,date}:{customers:Customer[];initialStops:Stop[];date:string}){
 const [position,setPosition]=useState<{lat:number;lng:number}|null>(null);const [selected,setSelected]=useState<string[]>(initialStops.length?initialStops.sort((a,b)=>a.position-b.position).map(s=>s.customer_id):[]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
 const ranked=useMemo(()=>customers.map(c=>({...c,distance_km:position&&c.latitude&&c.longitude?distance(position.lat,position.lng,Number(c.latitude),Number(c.longitude)):null})).sort((a,b)=>{const ad=a.distance_km??99999,bd=b.distance_km??99999;return (b.priority_score-a.priority_score)||(ad-bd);}),[customers,position]);
 async function locate(){setMsg('');try{const p=await getPosition();setPosition({lat:p.coords.latitude,lng:p.coords.longitude});setMsg('Sua localização foi usada para calcular as distâncias.');}catch{setMsg('Não foi possível acessar o GPS. Libere a localização do app e tente novamente.');}}
 function add(id:string){setSelected(s=>s.includes(id)?s:[...s,id])}function remove(id:string){setSelected(s=>s.filter(x=>x!==id))}function move(id:string,dir:number){setSelected(s=>{const i=s.indexOf(id),j=i+dir;if(i<0||j<0||j>=s.length)return s;const n=[...s];[n[i],n[j]]=[n[j],n[i]];return n})}
 async function save(){if(!selected.length)return setMsg('Adicione ao menos uma empresa ao roteiro.');setBusy(true);const reasons=Object.fromEntries(customers.map(c=>[c.id,c.priority_reason]));const scores=Object.fromEntries(customers.map(c=>[c.id,c.priority_score]));const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,customer_ids:selected,reasons,scores})});const j=await r.json();setMsg(r.ok?'Roteiro salvo com sucesso.':j.error||'Não foi possível salvar.');setBusy(false);if(r.ok)setTimeout(()=>location.reload(),500)}
 const chosen=selected.map(id=>ranked.find(c=>c.id===id)).filter(Boolean) as Customer[];
 return <><div className="route-actions card"><button className="btn btn-light" onClick={locate}><LocateFixed size={17}/>Usar minha localização</button><button className="btn btn-primary" onClick={save} disabled={busy}><Save size={17}/>{busy?'Salvando...':'Salvar roteiro'}</button>{msg&&<span className="route-message">{msg}</span>}</div><div className="route-grid"><section className="card route-suggestions"><div className="card-title"><div><h2>Clientes sugeridos</h2><p>Prioridade comercial combinada com proximidade.</p></div><Navigation/></div><div className="route-cards">{ranked.map(c=><article key={c.id} className="route-customer"><div><span className={`priority-pill p${Math.min(3,Math.ceil(c.priority_score/35))}`}>{c.priority_score>=70?'Alta':c.priority_score>=35?'Média':'Normal'}</span><h3>{c.trade_name||c.name}</h3><p><MapPin size={14}/>{[c.city,c.state].filter(Boolean).join(' / ')||'Cidade não informada'}{c.distance_km!==null&&c.distance_km!==undefined?` · ${c.distance_km.toFixed(1)} km`:''}</p><small>{c.priority_reason}</small></div><div className="route-customer-actions">{c.latitude&&c.longitude&&<a target="_blank" rel="noreferrer" className="btn btn-light btn-sm" href={`https://www.google.com/maps/dir/?api=1&destination=${c.latitude},${c.longitude}`}><Route size={15}/>Rota</a>}<button className="btn btn-primary btn-sm" disabled={selected.includes(c.id)} onClick={()=>add(c.id)}><Plus size={15}/>{selected.includes(c.id)?'Adicionado':'Adicionar'}</button></div></article>)}</div></section><section className="card route-today"><div className="card-title"><div><h2>Rota de hoje</h2><p>{chosen.length} parada(s) planejada(s).</p></div><Route/></div>{!chosen.length?<div className="map-empty"><Route size={30}/><b>Roteiro vazio</b><span>Adicione clientes sugeridos para montar seu dia.</span></div>:<ol className="route-stop-list">{chosen.map((c,i)=><li key={c.id}><span>{i+1}</span><div><b>{c.trade_name||c.name}</b><small>{c.priority_reason}</small></div><div className="route-order-actions"><button disabled={i===0} onClick={()=>move(c.id,-1)} title="Subir"><ArrowUp size={16}/></button><button disabled={i===chosen.length-1} onClick={()=>move(c.id,1)} title="Descer"><ArrowDown size={16}/></button><button onClick={()=>remove(c.id)} title="Remover"><Trash2 size={16}/></button></div></li>)}</ol>}{chosen[0]?.latitude&&chosen[0]?.longitude&&<a className="btn btn-primary route-next" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${chosen[0].latitude},${chosen[0].longitude}`}><Navigation size={17}/>Abrir próximo destino</a>}</section></div></>
}
