'use client';
import { useState } from 'react';
import { MessageCircle, Pencil, Plus, Trash2, X } from 'lucide-react';
import { useRouter } from 'next/navigation';

type Template={id:string;name:string;message:string;context:string;active:boolean};
const labels:Record<string,string>={geral:'Geral',reativacao:'Reativação',orcamento:'Orçamento',pedido:'Pedido',novidade:'Novidade'};
export default function WhatsAppTemplateManager({templates}:{templates:Template[]}){
 const router=useRouter();const[editing,setEditing]=useState<Template|null>(null);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 function add(){setEditing(null);setError('');setOpen(true)} function edit(t:Template){setEditing(t);setError('');setOpen(true)}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/admin/whatsapp-templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing?.id,name:f.get('name'),context:f.get('context'),message:f.get('message'),active:f.get('active')==='on'})});const j=await r.json();setLoading(false);if(!r.ok){setError(j.error||'Erro ao salvar.');return}setOpen(false);router.refresh()}
 async function remove(id:string){if(!confirm('Excluir este modelo de mensagem?'))return;await fetch(`/api/admin/whatsapp-templates?id=${id}`,{method:'DELETE'});router.refresh()}
 return <><div className="dashboard-card-head"><div><h2>Modelos de WhatsApp</h2><p>Use as variáveis <b>{'{cliente}'}</b>, <b>{'{vendedor}'}</b> e <b>{'{pedido}'}</b>.</p></div><button className="btn btn-primary" onClick={add}><Plus size={16}/>Novo modelo</button></div><div className="template-grid">{templates.map(t=><article className="template-card" key={t.id}><div className="template-card-head"><span className="badge">{labels[t.context]||t.context}</span><span className={t.active?'status-active':'status-inactive'}>{t.active?'Ativo':'Inativo'}</span></div><h3>{t.name}</h3><p>{t.message}</p><div className="template-actions"><button className="btn btn-light btn-sm" onClick={()=>edit(t)}><Pencil size={15}/>Editar</button><button className="btn btn-light btn-sm danger" onClick={()=>remove(t.id)}><Trash2 size={15}/>Excluir</button></div></article>)}</div>{open&&<div className="crm-modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="crm-modal wide" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOpen(false)}><X size={18}/></button><h3>{editing?'Editar modelo':'Novo modelo'}</h3><form className="form" onSubmit={save}><label>Nome<input className="input" name="name" defaultValue={editing?.name||''} required/></label><label>Contexto<select className="input" name="context" defaultValue={editing?.context||'geral'}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Mensagem<textarea className="input" name="message" rows={7} defaultValue={editing?.message||''} required/></label><label className="check-line"><input type="checkbox" name="active" defaultChecked={editing?.active??true}/>Modelo ativo</label>{error&&<div className="error">{error}</div>}<div className="crm-modal-buttons"><button type="button" className="btn btn-light" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn btn-primary" disabled={loading}><MessageCircle size={16}/>{loading?'Salvando...':'Salvar modelo'}</button></div></form></div></div>}</>
}
