import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, CheckCircle2, Clock3, Download, MapPin, Navigation, Route, Users } from "lucide-react";
import AppShell from "@/components/AppShell";
import { adminClient } from "@/lib/supabase-admin";
import { getCurrentProfile } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";
const dateTime = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" });
const outcomeLabels: Record<string,string> = { pedido_realizado:"Pedido realizado", proposta_enviada:"Proposta enviada", cliente_interessado:"Cliente interessado", retornar_depois:"Retornar depois", sem_interesse:"Sem interesse", cliente_fechado:"Cliente fechado", nao_localizado:"Cliente não localizado", sem_contato_responsavel:"Sem contato com responsável", outro:"Outro" };
const gpsReasonLabels: Record<string,string> = { gps_desligado:"GPS/localização desligado", permissao_bloqueada:"Permissão bloqueada", sem_sinal:"Sem sinal/localização indisponível", endereco_diferente:"Atendimento em endereço diferente", problema_aparelho:"Problema no aparelho", outro:"Outro" };
function duration(start:string,end?:string|null){ if(!end)return "Em andamento"; const min=Math.max(0,Math.round((new Date(end).getTime()-new Date(start).getTime())/60000)); return min<60?`${min} min`:`${Math.floor(min/60)}h ${min%60}min`; }
function distanceMeters(aLat:any,aLng:any,bLat:any,bLng:any){ if([aLat,aLng,bLat,bLng].some(v=>v===null||v===undefined||v===""))return null; const r=6371000; const toRad=(n:number)=>n*Math.PI/180; const p1=toRad(Number(aLat)); const p2=toRad(Number(bLat)); const dp=toRad(Number(bLat)-Number(aLat)); const dl=toRad(Number(bLng)-Number(aLng)); const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return Math.round(2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))); }

export default async function AdminVisitsPage({searchParams}:{searchParams:Promise<{from?:string;to?:string;seller?:string;status?:string;gps?:string;outcome?:string;q?:string}>}){
 const profile=await getCurrentProfile(); if(profile?.role!=="admin") redirect("/catalogo");
 const params=await searchParams; const now=new Date(); const first=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10); const from=params.from||first; const to=params.to||now.toISOString().slice(0,10);
 const db=adminClient();
 const {data:sellers}=await db.from("profiles").select("id,name").eq("role","vendedor").eq("active",true).order("name");
 let query=db.from("customer_visits").select("id,status,started_at,finished_at,start_latitude,start_longitude,end_latitude,end_longitude,accuracy_meters,end_accuracy_meters,start_gps_error_code,start_without_gps_reason,start_without_gps_details,end_gps_error_code,end_without_gps_reason,end_without_gps_details,outcome,outcome_code,notes,next_action,order_id,proposal_id,customer:customers!customer_visits_customer_id_fkey(id,name,trade_name,city,state),seller:profiles!customer_visits_seller_id_fkey(id,name)").gte("started_at",`${from}T00:00:00.000Z`).lte("started_at",`${to}T23:59:59.999Z`).order("started_at",{ascending:false}).limit(1000);
 if(params.seller) query=query.eq("seller_id",params.seller); if(params.status) query=query.eq("status",params.status); if(params.outcome) query=query.eq("outcome_code",params.outcome); if(params.gps==="com") query=query.not("start_latitude","is",null); if(params.gps==="sem") query=query.is("start_latitude",null);
 const {data,error}=await query; if(error) throw new Error(error.message);
 let visits=(data||[]) as any[]; if(params.q){const term=params.q.toLowerCase();visits=visits.filter(v=>`${v.customer?.trade_name||""} ${v.customer?.name||""} ${v.customer?.city||""} ${v.seller?.name||""}`.toLowerCase().includes(term));}
 const completed=visits.filter(v=>v.status==="concluida"); const active=visits.filter(v=>v.status==="em_andamento"); const withGps=visits.filter(v=>v.start_latitude&&v.start_longitude); const withoutGps=visits.filter(v=>!v.start_latitude||!v.start_longitude); const converted=completed.filter(v=>["pedido_realizado","proposta_enviada"].includes(v.outcome_code)); const avg=completed.length?Math.round(completed.reduce((s,v)=>s+Math.max(0,(new Date(v.finished_at).getTime()-new Date(v.started_at).getTime())/60000),0)/completed.length):0;
 const qs=new URLSearchParams(Object.entries({...params,from,to}).filter(([,v])=>v) as [string,string][]).toString();
 return <AppShell>
  <div className="page-head"><div><span className="eyebrow">GESTÃO COMERCIAL</span><h1>Visitas e geolocalização</h1><p>Acompanhe check-ins, check-outs, precisão, exceções sem GPS e conversão da equipe externa.</p></div><Link className="btn btn-primary" href={`/api/admin/export/visitas?${qs}`}><Download size={17}/>Exportar CSV</Link></div>
  <form className="card visit-report-filter" method="get"><label>Data inicial<input type="date" name="from" defaultValue={from}/></label><label>Data final<input type="date" name="to" defaultValue={to}/></label><label>Vendedor<select name="seller" defaultValue={params.seller||""}><option value="">Todos</option>{(sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Status<select name="status" defaultValue={params.status||""}><option value="">Todos</option><option value="em_andamento">Em andamento</option><option value="concluida">Concluída</option><option value="cancelada">Cancelada</option></select></label><label>GPS<select name="gps" defaultValue={params.gps||""}><option value="">Todos</option><option value="com">Com GPS</option><option value="sem">Sem GPS</option></select></label><label>Resultado<select name="outcome" defaultValue={params.outcome||""}><option value="">Todos</option>{Object.entries(outcomeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="visit-search">Empresa, cidade ou vendedor<input name="q" defaultValue={params.q||""} placeholder="Buscar..."/></label><button className="btn btn-primary" type="submit"><Navigation size={17}/>Aplicar filtros</button></form>
  <section className="visit-report-kpis"><div className="card"><MapPin/><span>Visitas no período</span><strong>{visits.length}</strong></div><div className="card"><CheckCircle2/><span>Concluídas</span><strong>{completed.length}</strong></div><div className="card"><Route/><span>Com GPS</span><strong>{withGps.length}</strong></div><div className="card"><AlertTriangle/><span>Sem GPS</span><strong>{withoutGps.length}</strong></div><div className="card"><Clock3/><span>Duração média</span><strong>{avg} min</strong></div><div className="card"><Users/><span>Em andamento</span><strong>{active.length}</strong></div></section>
  <section className="card visit-report-table-card"><div className="table-wrap"><table className="visit-report-table"><thead><tr><th>Data</th><th>Vendedor</th><th>Empresa</th><th>Duração</th><th>GPS</th><th>Resultado</th><th>Status</th><th>Vínculo</th></tr></thead><tbody>{!visits.length?<tr><td colSpan={8} className="empty">Nenhuma visita encontrada.</td></tr>:visits.map(v=>{const moved=distanceMeters(v.start_latitude,v.start_longitude,v.end_latitude,v.end_longitude);return <tr key={v.id}><td><b>{dateTime.format(new Date(v.started_at))}</b>{v.finished_at&&<small>Fim: {dateTime.format(new Date(v.finished_at))}</small>}</td><td>{v.seller?.name||"—"}</td><td><Link href={`/empresas/${v.customer?.id}`}>{v.customer?.trade_name||v.customer?.name||"—"}</Link><small>{[v.customer?.city,v.customer?.state].filter(Boolean).join("/")}</small></td><td>{duration(v.started_at,v.finished_at)}</td><td>{v.start_latitude&&v.start_longitude?<><a className="map-link" target="_blank" href={`https://www.google.com/maps?q=${v.start_latitude},${v.start_longitude}`}><MapPin size={15}/>Check-in</a>{v.accuracy_meters&&<small>Precisão inicial: {Math.round(Number(v.accuracy_meters))} m</small>}</>:<><span className="gps-warning-text">Sem GPS no início</span>{v.start_without_gps_reason&&<small className="gps-reason">{gpsReasonLabels[v.start_without_gps_reason]||v.start_without_gps_reason}{v.start_without_gps_details?`: ${v.start_without_gps_details}`:""}</small>}</>}{v.end_latitude&&v.end_longitude&&<><a className="map-link" target="_blank" href={`https://www.google.com/maps?q=${v.end_latitude},${v.end_longitude}`}><MapPin size={15}/>Check-out</a>{v.end_accuracy_meters&&<small>Precisão final: {Math.round(Number(v.end_accuracy_meters))} m</small>}</>}{v.finished_at&&!v.end_latitude&&v.status==="concluida"&&<><small className="gps-warning-text">Sem GPS no término</small>{v.end_without_gps_reason&&<small className="gps-reason">{gpsReasonLabels[v.end_without_gps_reason]||v.end_without_gps_reason}{v.end_without_gps_details?`: ${v.end_without_gps_details}`:""}</small>}</>}{moved!==null&&<small className="gps-distance">Distância início/fim: {moved<1000?`${moved} m`:`${(moved/1000).toFixed(2)} km`}</small>}</td><td><b>{outcomeLabels[v.outcome_code]||v.outcome||"—"}</b>{v.notes&&<small title={v.notes}>{v.notes.length>70?v.notes.slice(0,70)+"…":v.notes}</small>}</td><td><span className={`visit-status ${v.status}`}>{v.status.replaceAll("_"," ")}</span></td><td>{v.order_id?<Link href={`/pedidos/${v.order_id}`}>Pedido</Link>:v.proposal_id?<Link href={`/propostas/${v.proposal_id}`}>Proposta</Link>:"—"}</td></tr>})}</tbody></table></div></section>
 </AppShell>
}
