import { redirect } from 'next/navigation';
import { AlertTriangle, Building2, CheckCircle2, MapPinned, Navigation, Users } from 'lucide-react';
import AppShell from '@/components/AppShell';
import CommercialMap from '@/components/CommercialMap';
import { adminClient } from '@/lib/supabase-admin';
import { getCurrentProfile } from '@/lib/supabase-server';

export const dynamic='force-dynamic';
function daysSince(value?:string|null){if(!value)return 9999;return Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));}
export default async function CommercialMapPage({searchParams}:{searchParams:Promise<{seller?:string;state?:string;status?:string;q?:string}>}){
 const profile=await getCurrentProfile();if(profile?.role!=='admin')redirect('/catalogo');const params=await searchParams;const db=adminClient();
 const [{data:customers},{data:sellers},{data:visits}]=await Promise.all([
  db.from('customers').select('id,name,trade_name,city,state,seller_id,active,latitude,longitude,visit_radius_meters').order('name'),
  db.from('profiles').select('id,name').eq('role','vendedor').eq('active',true).order('name'),
  db.from('customer_visits').select('customer_id,started_at,status').order('started_at',{ascending:false}).limit(5000)
 ]);
 const sellerMap=new Map((sellers||[]).map(s=>[s.id,s.name]));const lastVisit=new Map<string,string>();for(const v of visits||[])if(v.customer_id&&!lastVisit.has(v.customer_id))lastVisit.set(v.customer_id,v.started_at);
 let rows=(customers||[]).map((c:any)=>{const last=lastVisit.get(c.id)||null;const days=daysSince(last);let status_label='Visitada recentemente',status_color='#16a34a',priority_reason='Carteira em dia';if(!c.latitude||!c.longitude){status_label='Localização pendente';status_color='#64748b';priority_reason='Cadastre as coordenadas da empresa';}else if(!c.active){status_label='Empresa inativa';status_color='#64748b';priority_reason='Cadastro inativo';}else if(days>=90){status_label='Prioridade crítica';status_color='#dc2626';priority_reason=last?`${days} dias sem visita`:'Nunca visitada';}else if(days>=30){status_label='Precisa de atenção';status_color='#f59e0b';priority_reason=`${days} dias sem visita`;}return {...c,seller_name:c.seller_id?sellerMap.get(c.seller_id)||null:null,last_visit:last,days_without_visit:days,status_label,status_color,priority_reason,href:`/admin/clientes/${c.id}`};});
 if(params.seller)rows=rows.filter(r=>r.seller_id===params.seller);if(params.state)rows=rows.filter(r=>r.state===params.state);if(params.status==='pendente')rows=rows.filter(r=>!r.latitude||!r.longitude);if(params.status==='critico')rows=rows.filter(r=>r.days_without_visit>=90&&r.latitude&&r.longitude);if(params.status==='atencao')rows=rows.filter(r=>r.days_without_visit>=30&&r.days_without_visit<90);if(params.q){const q=params.q.toLowerCase();rows=rows.filter(r=>`${r.name} ${r.trade_name||''} ${r.city||''} ${r.state||''} ${r.seller_name||''}`.toLowerCase().includes(q));}
 const mapped=rows.filter(r=>r.latitude&&r.longitude);const pending=rows.length-mapped.length;const critical=rows.filter(r=>r.days_without_visit>=90&&r.latitude&&r.longitude).length;const recent=rows.filter(r=>r.days_without_visit<30&&r.latitude&&r.longitude).length;const states=Array.from(new Set((customers||[]).map((c:any)=>c.state).filter(Boolean))).sort();
 return <AppShell><div className="page-head"><div><span className="eyebrow">GESTÃO TERRITORIAL</span><h1>Mapa comercial</h1><p>Visualize a cobertura da carteira, empresas prioritárias e localizações pendentes.</p></div></div>
 <form className="card map-filter" method="get"><label>Buscar<input name="q" defaultValue={params.q||''} placeholder="Empresa, cidade ou vendedor"/></label><label>Vendedor<select name="seller" defaultValue={params.seller||''}><option value="">Todos</option>{(sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>UF<select name="state" defaultValue={params.state||''}><option value="">Todas</option>{states.map(s=><option key={String(s)} value={String(s)}>{String(s)}</option>)}</select></label><label>Situação<select name="status" defaultValue={params.status||''}><option value="">Todas</option><option value="critico">Prioridade crítica</option><option value="atencao">Precisa de atenção</option><option value="pendente">Localização pendente</option></select></label><button className="btn btn-primary"><Navigation size={17}/>Aplicar</button></form>
 <section className="map-kpis"><div className="card"><Building2/><span>Empresas filtradas</span><strong>{rows.length}</strong></div><div className="card"><MapPinned/><span>No mapa</span><strong>{mapped.length}</strong></div><div className="card"><AlertTriangle/><span>Localização pendente</span><strong>{pending}</strong></div><div className="card"><Users/><span>Prioridade crítica</span><strong>{critical}</strong></div><div className="card"><CheckCircle2/><span>Visitadas em 30 dias</span><strong>{recent}</strong></div></section>
 <section className="card map-card"><CommercialMap points={rows as any}/></section>
 <section className="card table-wrap"><table><thead><tr><th>Empresa</th><th>Vendedor</th><th>Cidade</th><th>Última visita</th><th>Situação</th><th>Coordenadas</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><a href={`/admin/clientes/${r.id}`}><b>{r.trade_name||r.name}</b></a></td><td>{r.seller_name||'Sem vendedor'}</td><td>{[r.city,r.state].filter(Boolean).join(' / ')||'—'}</td><td>{r.last_visit?new Date(r.last_visit).toLocaleDateString('pt-BR'):'Nunca'}</td><td><span className="map-status" style={{borderColor:r.status_color,color:r.status_color}}>{r.status_label}</span><small>{r.priority_reason}</small></td><td>{r.latitude&&r.longitude?<a target="_blank" href={`https://www.google.com/maps?q=${r.latitude},${r.longitude}`}>Abrir mapa</a>:<span className="gps-warning-text">Pendente</span>}</td></tr>)}</tbody></table></section></AppShell>
}
